# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'prometheus'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
# rule_files:
#   - "alert.rules"
#
# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090','cadvisor:8080']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']


  # - job_name: 'datasources'
  #   static_configs:
  #     - targets: ['<mysql_node>:9104', '<es_node>:9108' ]

    # Override the global default and scrape targets from this job every 5 seconds.
    # scrape_interval: 5s

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    # consul_sd_configs:
    #   - server: <consul_api_url>:8500
    #     services:
    #       - docker-node

    # relabel_configs:
    #   - source_labels: [ __meta_consul_tags ]
    #     regex: '.*,noagent,.*'
    #     action: drop
    #
    #   # Set node name lable
    #   - source_labels: [__meta_consul_node]
    #     target_label:  node
    #
    #   # Set metrics address
    #   - source_labels: [__meta_consul_address]
    #     regex: '(.*)'
    #     replacement: $1:720
    #     target_label:  __address__
    #
    #   # Set runtime_env
    #   - source_labels: [__meta_consul_tags]
    #     regex: '.*,account_(.+?),.*'
    #     replacement: $1
    #     target_label:  runtime_env
    #
    #   # Set role
    #   - source_labels: [__meta_consul_tags]
    #     regex: '.*,type_(.+?),.*'
    #     replacement: $1
    #     target_label:  node_role
